name: linear_progress_bar
description: A powerful and customizable progress indicator library for Flutter. Supports linear bars, circular percent indicators, gauges, dots indicators, titled progress, gradients, and animations.
version: 3.0.0
homepage: https://www.angopapo.com
repository: https://github.com/Angopapo/linear_progress_bar
issue_tracker: https://github.com/Angopapo/linear_progress_bar/issues

topics:
  - progress
  - indicator
  - ui
  - widget

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
